In [ ]:
#importing necessary libraries

import pandas as pd
import numpy as np

In [ ]:
#loading the dataset

df =pd.read_csv('Superstore.csv', encoding='latin-1')

In [ ]:
#checking the structure of the dataset

df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2.0,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3.0,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2.0,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5.0,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2.0,0.20,2.5164

In [ ]:
#checking for null values

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   str
 3   Ship Date      9994 non-null   str
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   str
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   float64
 19  Discount       9991 non-null   float64
 20  Profit         9981 non-null   float64
dtypes: float64(4), int64(1), str(16)
memory usage: 1.6 MB

In [ ]:
#counting the number of null values in each column

df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code       0
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
Quantity          0
Discount          3
Profit           13
dtype: int64

In [ ]:
#dropping the rows with null values

df = df.dropna()

In [ ]:
#checking for duplicate values

df.duplicated().sum()

np.int64(0)

In [ ]:
#converting the 'Order Date' column to datetime format

df['Order Date'] = pd.to_datetime(df['Order Date'])

In [ ]:
#creating a new column 'Total Sales' by multiplying 'Sales' and 'Quantity'

df['Total Sales'] = df['Sales'] * df['Quantity']

In [ ]:
#checking the summary statistics of the dataset
df.describe()

,Row ID,Order Date,Sales,Quantity,Discount,Profit,Total Sales
count,9981.000000,9981,9981.000000,9981.000000,9981.000000,9981.000000,9981.000000
mean,5003.982667,2016-04-30 08:34:02.921551,229.547684,3.789400,0.155965,28.854530,1146.796960
min,1.000000,2014-01-03 00:00:00,0.444000,1.000000,0.000000,-6599.978000,0.444000
25%,2509.000000,2015-05-23 00:00:00,17.300000,2.000000,0.000000,1.732500,48.712000
50%,5004.000000,2016-06-26 00:00:00,54.528000,3.000000,0.200000,8.671500,183.750000
75%,7499.000000,2017-05-14 00:00:00,209.940000,5.000000,0.200000,29.364000,763.250000
max,9994.000000,2017-12-30 00:00:00,22638.480000,14.000000,0.800000,8399.976000,135830.880000
std,2881.440861,NaN,622.751163,2.225407,0.206275,233.791364,3893.022194

In [ ]:
#saving the cleaned dataset to a new CSV file

df.to_csv("cleaned_sales.csv", index=False)